[template.environment]
#Variables for Contentful
CONTENTFUL_SPACE_ID = "CONTENTFUL_SPACE_ID"
CONTENTFUL_ACCESS_TOKEN = "CONTENTFUL_ACCESS_TOKEN"
CONTENTFUL_ENVIRONMENT_ID = "CONTENTFUL_ENVIRONMENT_ID"
CONTENTFUL_MANAGEMENT_TOKEN = "CONTENTFUL_MANAGEMENT_TOKEN"
CONTENTFUL_REVALIDATE_SECRET = "CONTENTFUL_REVALIDATE_SECRET"

[[plugins]]
package = "/plugins/contentful-setup"
